### PR TITLE
Fixing step 1c so that words like key and say are not stemmed to kei and...

### PR DESCRIPTION
**Pull request by dwcramer**
... sai and words like try are stemmed to tri. sky is listed as a special case in porter 2.

### CODE REVIEW

**Comment by dwcramer** [comment]
Note that "skies" should be stemmed to "sky" but isn't. I wasn't sure how to change that. 

Thanks,
David

**Comment by kristopolous** [comment]
Although I see that your solution is correct and yields a better stemmer ... I'll have to reference Martin Porter's literature first ... unless you can give me a citation.  This project is the official JS reference porter stemmer so I have to be pretty careful on what I do here.  Thanks.

**Comment by dwcramer** [comment]
Sure thing. I'm going off of this page (and the results of the Java stemmer that we use to index our content at build time. We use the js stemmer on the client side to stem the search term, so differences between the two cause problems):

http://snowball.tartarus.org/algorithms/english/stemmer.html

In particular, see:

"Step 1c: *
replace suffix y or Y by i if preceded by a non-vowel which is not the first letter of the word (so cry -> cri, by -> by, say -> say) "

and 

"Exceptional forms in general"
...
// ... extensions possible here ...

/\* invariant forms: */

'sky'
..."

**Comment by kristopolous** [comment]
ok great! Sounds right to me too ... I should probably get a validation suite up and running sometime soon.  Thanks for your work! I'll update the demo site too ... but not right now.

**Pull request merged**
