### PR TITLE
Use hasOwnProperty to test if property exists

### PR DESCRIPTION
**Pull request by albertsun**
Trying things like:

stemmer("**proto**")

Or in Firefox

stemmer("watch")

Or other things that are properties of an object instance (https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Object) and the stemmer will return the object function instead of a string.

### CODE REVIEW

**Comment by kristopolous** [comment]
Nice catch but I can't accept this because hasOwnProperty isn't supported below IE10.  I'll implement it another way though. Thanks!

**Comment by albertsun** [comment]
I don't have IE on the computer I'm at right now, but I'm pretty sure older IE's only lack hasOwnProperty for DOM elements. For plain javascript objects it should be there. See: http://msdn.microsoft.com/en-us/library/328kyd6z%28v=vs.94%29

**Comment by kristopolous** [comment]
Oh, I believe you may be correct there now that I think of it. Regardless, there has been some major revamping of the entire project in the past two hours or so ... see https://github.com/kristopolous/Porter-Stemmer/commit/e990a8d456510571d1ef9ef923d2a30a94679e13 for more info.

Basically, I took a large mess of code in 2009 and then went through and did some audits and then sent it back to Martin Porter, who then christened me as the maintainer.  However, I had never actually validated the code I inherited until today.

There were some surprises.

Those have been clarified and now we should have a much better handle on what this stuff does.  Sorry again for the earlier confusion.

**Comment by albertsun** [comment]
Cool. New version looks promising, looking forward to seeing to get to 100%
compliant.

On Thu, Sep 6, 2012 at 10:22 PM, Chris McKenzie notifications@github.comwrote:

> Oh, I believe you may be correct there now that I think of it. Regardless,
> there has been some major revamping of the entire project in the past two
> hours or so ... see
> https://github.com/kristopolous/Porter-Stemmer/commit/e990a8d456510571d1ef9ef923d2a30a94679e13for more info.
> 
> Basically, I took a large mess of code in 2009 and then went through and
> did some audits and then sent it back to Martin Porter, who then christened
> me as the maintainer. However, I had never actually validated the code I
> inherited until today.
> 
> There were some surprises.
> 
> Those have been clarified and now we should have a much better handle on
> what this stuff does. Sorry again for the earlier confusion.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kristopolous/Porter-Stemmer/pull/4#issuecomment-8354095.

## 

Albert Sun
albert@albertsun.info
215.253.8566

**Pull request closed without merging**
